Adding CONTRIBUTING.md
Awesome-React-Modules/React-Pincode-Website pull request #7
Opened 2020-03-20 19:31 UTC by Kuljeet-123

Fixes issue:- #4

2020-03-22 10:29 UTC, Kuljeet-123 commented
@yellowwoods12  it's been 2 days ...please review my PR and merge it.

2020-03-26 08:06 UTC, yellowwoods12 approved these changes

2020-03-31 13:55 UTC, Kuljeet-123 commented
@yellowwoods12 Could you please merge it...It's been 11 days.

2020-03-31 16:18 UTC, plxity requested changes
Please make this file same as in React-Pincode. We have to maintain the uniformity across all about projects.

2020-03-31 16:18 UTC, plxity commented on CONTRIBUTING.md
> +The workflow that we'll be using is <b> Dev - Staging - Production</b>. All the Pull Request (PR's) will be made to <b>develop</b> branch.
@Kuljeet-123 Change the branch name to master.

2020-03-31 17:32 UTC, Kuljeet-123 commented
@plxity I have update the changes you requested.Please review it.

2020-04-01 06:12 UTC, plxity commented
> Please make this file same as in React-Pincode. We have to maintain the uniformity across all about projects.

@Kuljeet-123 please make the changes.

2020-04-01 06:35 UTC, Kuljeet-123 commented
@plxity I have update the changes you requested.Please review it.

2020-04-01 06:39 UTC, yellowwoods12 approved these changes

2020-04-01 20:19 UTC, plxity approved these changes

2020-04-01 20:19 UTC, merged